### PR TITLE
Add templating for the validation email

### LINKED ISSUE #9: Incorrect charset at email after posting for new account
image

### PR DESCRIPTION
**Pull request by kerel-fs**
Probably fixes #9, can't test it.

### CODE REVIEW

**Comment by snip** [comment]
Not better for encoding.
- There is no more subject to mail sent.
- mail content is sent in HTML format (but something should be wrong as it is not interpreted as html) instead of plain text.
  Tested in French language.

**Comment by kerel-fs** [comment]
Both issues should be resolved now (tested locally with [Scotch Box](https://box.scotch.io/) and [MailCatcher](http://mailcatcher.me/)).

**Comment by snip** [comment]
Correct: both issues seems solved. So email is correct.
But there is still the charset issue on webpage.
Here is what i get once form submitted:

```
<html><head></head><body><center>
Un courriel vous a Ã©tÃ© envoyÃ©, vous trouverez les instruction pour valider votre compte.
</center>
</body></html>
```

**Comment by kerel-fs** [comment]
Latest commit should fix those encoding issues.

**Pull request merged**
