### PR TITLE
Moved HTML to template-files and language arrays to language-files

### PR DESCRIPTION
**Pull request by dbursem**
I'd like to make some better templates, so to make a start I moved all the HTML to Twig template files to make both the PHP and HTML code better maintainable. 
Twig can be installed by running `composer update` in the install directory. 
check http://getcomposer.org and http://twig.sensiolabs.org for more info if needed

Maybe it'll be worth to port all code to Symfony2 but that would be a lot of work, don't know if it 'll pay off.

### CODE REVIEW

**Comment by kerel-fs** [comment]
Nice work, imho using twig/jinja2-templates is indeed the first step towards a nicer interface.
Maybe you should provide a description on how to deploy this site with twig in the README.

Filtering should be done in the client, as the whole data should be cached by clients (eg. as currently done by `rtlsdr-ogn`).

**Comment by dbursem** [comment]
Thanks for the feedback. Indeed a good idea to put that in the readme.
I think rtlsdr-ogn only needs the list of tracked devices, so thats one way to apply filtering to save some bandwidth. 
I can also see some possibilities for my own aprs client, and who knows what possibilities other people will come up with once there's a good api.

**Comment by kerel-fs** [comment]
Please don't clutter your PullRequest with changes from other PullRequests, git solves such conflicts automatically. If really needed (I don't think so), I will rebase my PR after your gets merged (or the other way around).

**Comment by kerel-fs** [comment]
It would be a good idea to move commits introducing new functionality to another PullRequest.

If we want to serve the file in other formats (eg. JSON, imho this is superfluous), we should create separate endpoints (like it has been done for `download-fln.php`).

A possible format of a`download.json` could be:
https://gist.github.com/kerel-fs/6178879a7ddf5e4479b3

**Comment by dbursem** [comment]
The JSON output is already in the main branch, I just cleaned it up a
little.

If it's up to me we change the spec a little, I think it's kind of ugly to
convert booleans to "Y"/"N" strings for example. But the same is true for
the CSV output.

I disagree with the differend endpoint. The format of data is arbitrary and
should be specified by the user via the HTTP accept header.
The FLN output might be an exception as it's a non-standard format and it
only contains a subset of the data. One might also argue that the t=1
filter should not be a filter but a different endpoint, because setting it
changes the subset of data.

If we want to move to a full blown REST API I think the best way is to
rewrite the whole code as a Symfony2 project, as it has all the tools and
plugins to handle calls, automatically create documentation, handle
authorisation, etc etc etc.

Met vriendelijke groeten,

David Ursem

**Comment by kerel-fs** [comment]
Sorry, I overlooked the existing JSON output.

In its current form, its usability is greatly limited, as a client
has to parse the values, neglecting the advantages of JSON.
Though we shouldn't change the specs of existing endpoints
unless we know nobody is using it (--> mailing list?).

I agree with your argumentation regarding different endpoints,
my goal was to keep it consistent, but as you stated,
download-fln.php is an exception.

As previously said, imho a 'full blown REST API' is greatly
superfluous concerning the simplicity of the data.

**Comment by dbursem** [comment]
Are there any plans to merge this and other pull requests? Or is there anything we can do to help or need to change to make this possible? 

I'd be willing to help installing or managing the DDB if necessary.

**Comment by kerel-fs** [comment]
@cunimb / @snip: Any news on this and other PRs?

**Comment by snip** [comment]
I'm looking at merging this code, but:
- Can you please rebase to have only one commit per feature?
- Fix conflicts with latest version?

Thanks for your contribution.
(No promise about the merge but i will at least get a try)

**Comment by kerel-fs** [comment]
I've done a rebase here: https://github.com/kerel-fs/ogn-ddb/tree/fix-dbursem/master
It does not contain some unwanted changes (eg. changed ddb.glidernet.org to localhost).

**Comment by dbursem** [comment]
Thank you so much kerel-fs. I know I should have a letter git routine, I'll try to work on that.

**Comment by snip** [comment]
in index.php you:
`require_once 'vendor/autoload.php';`

but this file doesn't exist. Is it possible to correct this?

**Comment by kerel-fs** [comment]
Composer generates `vendor/autoload.php` during the installation of dependencies.

**Comment by snip** [comment]
Put in production.
Thanks for your help.

**Comment by dbursem** [comment]
Thank you very much guys!

**Pull request closed without merging**
